name: 🔍 IntroducedBy Checker 🔍
on:
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs: 
  compliance_test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: IntroducedBy Checker
    permissions:
       pull-requests: write
       contents: write
    steps:
      - name: Checkout # Makes the source code available to be scanned
        id:   checkout
        uses: actions/checkout@v4 
      - name: Delete marked package references # Scans the source code for marked package references and deletes them
        id:   scan
        uses: equinor/introducedby-checker@main # Whatever is the head in the main branch. We control the repository for the action, so we can control the risk of not using a release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}