name: "Equinor Compliance Check"

on:
  push:

jobs: 
  compliance_test:
    runs-on: ubuntu-latest
    name: Compliance test
    permissions:
      issues:   write
      contents: read
    steps:
      - name: Checkout # Makes the source code available to be scanned
        id:   checkout
        uses: actions/checkout@v4 
      - name: Scan repo # Scans the source code and repo for compliance
        id:   scan
        uses: equinor/it-compliance-action@v0.2.3-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}